Extended support for ACL2 packages by adding generated file examples/acl2/tests/inputs/PKGS.ml.

diff --git a/examples/acl2/tests/doit b/examples/acl2/tests/doit
--- a/examples/acl2/tests/doit
+++ b/examples/acl2/tests/doit
@@ -23,16 +23,18 @@ if [ "$my_args" = "clean+" ]; then \
 fi
 
 if [ "$my_args" = "clean" ]; then \
-    rm diffout diffout.old ; \
+    rm -f diffout diffout.old 2> /dev/null ; \
     rm -rf $results_dir $old_results_dir $logs_dir $old_logs_dir ; \
     cd $inputs_dir ; make clean ; cd .. ; \
     cd round-trip ; ./doit clean ; cd .. ; \
     exit 0 ; \
 fi
 
-echo "Making books in $lisp_dir..." ; cd $lisp_dir ; make ; cd ..
+echo "Making books in $lisp_dir..." ; cd $lisp_dir ; make -s ; temp_status=$? ; cd ..
+if [ $temp_status -ne 0 ]; then echo "***Failure making books in $lisp_dir" ; my_status=1 ; fi
 
-echo "Making books in $inputs_dir..." ; cd $inputs_dir ; make ; cd ..
+echo "Making books in $inputs_dir..." ; cd $inputs_dir ; make -s ; temp_status=$? ; cd ..
+if [ $temp_status -ne 0 ]; then echo "***Failure making books in $inputs_dir" ; my_status=1 ; fi
 
 echo "Converting .lisp files to their essences..."
 
diff --git a/examples/acl2/tests/inputs/Makefile b/examples/acl2/tests/inputs/Makefile
--- a/examples/acl2/tests/inputs/Makefile
+++ b/examples/acl2/tests/inputs/Makefile
@@ -1,10 +1,38 @@
-CERTS := $(patsubst %.lisp, %.cert, $(wildcard *.lisp))
+TMPFILE = /tmp/workxxx
 
-.PHONY: top
-top: $(CERTS)
+top: pkg-check.txt
 
 include ${ACL2_SYSTEM_BOOKS}/Makefile-generic
 # The following line shouldn't be necessary.
 ACL2 ?= acl2
 
 -include Makefile-deps
+
+pkg-check.txt: PKGS.lsp PKGS.ml
+	@echo '(include-book "../../lisp/pkg-alist-to-alist")' > $(TMPFILE)
+	@echo "(ld (quote (" >> $(TMPFILE)
+	@for book in $(BOOKS) ; \
+	do \
+	echo "(include-book \"$$book\")" >> $(TMPFILE) ; \
+	echo '(chk-known-package-alist "PKGS.lsp" state)' >> $(TMPFILE) ; \
+	echo '(u)' >> $(TMPFILE) ; \
+	done
+	@echo "(note-chk-known-package-alist-success \"pkg-check.txt\" state)" >> $(TMPFILE)
+	@echo ")))" >> $(TMPFILE)
+	@$(ACL2) < $(TMPFILE) > pkg-check.out 2> pkg-check.err
+	@if [ ! -e pkg-check.txt ]; then \
+	echo "FAILURE for pkg-check.txt" ; \
+	exit 1 ; \
+	fi
+
+PKGS.lsp PKGS.ml: all
+	echo '(include-book "../../lisp/pkg-alist-to-alist")' > $(TMPFILE)
+	echo '(include-book "pkg-test")' >> $(TMPFILE)
+	echo '(include-book "m1-story")' >> $(TMPFILE)
+	echo '(print-kpa "PKGS.lsp" "PKGS.ml")' >> $(TMPFILE)
+	$(ACL2) < $(TMPFILE) > PKGS.out 2> PKGS.err
+
+clean: clean-pkgs
+
+clean-pkgs:
+	rm -f PKGS.* pkg-check.*
