----------------------------------------------------------------------
Committing in revisions to several libraries so that the documentation
builds, and is then presented at the top level when the exported version
of HOL4 is built (as for the public version we are about to release).

This documentation is obviously very much out of date, and yet it still
is greatly useful for people who wish to use these libraries.  While
waiting for fully updated versions, I believe this is far better than
not including these, as much of the content does not appear elsewhere.

Modified Files:
	hol98/developers/releasing-hol
	hol98/src/num/arith/Manual/Makefile
	hol98/src/num/arith/Manual/entries.tex
	hol98/src/num/reduce/Manual/Makefile
	hol98/src/num/reduce/Manual/index.tex
	hol98/src/num/reduce/Manual/reduce.tex
	hol98/src/pair/Manual/Makefile
	hol98/src/pred_set/Manual/index.tex
	hol98/src/res_quan/Manual/Makefile
	hol98/src/string/Manual/Makefile
	hol98/src/taut/Manual/Makefile
	hol98/src/unwind/Manual/Makefile
	hol98/src/unwind/Manual/entries.tex
	hol98/src/unwind/Manual/index.tex
	hol98/src/unwind/Manual/unwind.tex
	hol98/src/word/Manual/Makefile hol98/src/word/Manual/index.tex
Added Files:
	hol98/src/string/help/defs/ASCII_DEF.doc
	hol98/src/string/help/defs/STRING_DEF.doc
	hol98/src/string/help/defs/``_DEF.doc
	hol98/src/string/help/defs/ascii_ISO_DEF.doc
	hol98/src/string/help/defs/ascii_TY_DEF.doc
	hol98/src/string/help/defs/string_ISO_DEF.doc
	hol98/src/string/help/defs/string_TY_DEF.doc
	hol98/src/string/help/thms/ASCII_11.doc
	hol98/src/string/help/thms/NOT_EMPTY_STRING.doc
	hol98/src/string/help/thms/NOT_STRING_EMPTY.doc
	hol98/src/string/help/thms/STRING_11.doc
	hol98/src/string/help/thms/ascii_Axiom.doc
	hol98/src/string/help/thms/ascii_CASES.doc
	hol98/src/string/help/thms/ascii_Induct.doc
	hol98/src/string/help/thms/string_Axiom.doc
	hol98/src/string/help/thms/string_CASES.doc
	hol98/src/string/help/thms/string_Induct.doc
----------------------------------------------------------------------

diff --git a/developers/releasing-hol b/developers/releasing-hol
--- a/developers/releasing-hol
+++ b/developers/releasing-hol
@@ -104,7 +104,7 @@ do
     mv HolSatLib$i /tmp/$name-HolSatLib$i
 done
 
-for lib_name in pred_set
+for lib_name in pred_set pair res_quan string taut unwind word
 do
     echo Building $lib_name documentation
     cd /tmp/hol98/src/$lib_name/Manual
@@ -113,6 +113,22 @@ do
        :
     else
        echo "Build failed, see /tmp/$lib_name-latex.log" ; exit 1
+    fi
+    for i in .dvi .ps .pdf
+    do
+        mv $lib_name$i /tmp/$name-$lib_name$i
+    done
+done
+
+for lib_name in arith reduce
+do
+    echo Building num/$lib_name documentation
+    cd /tmp/hol98/src/num/$lib_name/Manual
+    if (make all) > /tmp/num-$lib_name-latex.log 2>&1
+    then
+       :
+    else
+       echo "Build failed, see /tmp/num-$lib_name-latex.log" ; exit 1
     fi
     for i in .dvi .ps .pdf
     do
