Ported revisions 8497:8608 (via 8549) from HOL to HOL-Omega. This is to keep HOL-Omega current with the latest HOL developments.

diff --git a/developers/releasing-hol b/developers/releasing-hol
--- a/developers/releasing-hol
+++ b/developers/releasing-hol
@@ -5,27 +5,30 @@ homesvn=https://hol.svn.sourceforge.net/svnroot/hol
 # typical usage: ./releasing-hol -f branches/HOL-Omega Kananaskis-5 `which poly`
 
 usage () {
-        echo "Usage: releasing-hol [-f] <release-path> <verson> <ML>" >&2
+        echo "Usage: releasing-hol [-f] [--svn URL] <release-path> <verson> <ML>" >&2
         echo "  <release-path> is a path wrt $homesvn" >&2
         echo "  <version> is a version name, e.g. kananaskis-5" >&2
         echo "  <ML> is a path to mosml or poly" >&2
         echo "  Use the -f option to force fresh svn call (ignoring cache)" >&2
+        echo "  Use --svn <repo-URL> to specify alternative svn repo" >&2
         exit 1
 }
 
-if [ $# -eq 0 ]
-then
-    usage
-fi
+TEMP=$(getopt -n releasing-hol -of -l svn: -- "$@")
+eval set -- "$TEMP"
 
-if [ $1 = "-f" ]
-then
-    force=true
-    echo "Forcing a fresh svn export call" >&2
-    shift
-else
-    force=false
-fi
+force=false
+
+while true
+do
+    case "$1" in
+        -f ) force=true ; echo "Forcing a fresh svn export call" >&2; shift ;;
+        --svn ) homesvn=$2 ; shift 2 ;;
+        -- ) shift ; break ;;
+        * ) echo "Internal error!" >&2 ; exit 1 ;;
+    esac
+done
+
 
 if [ $# -ne 3 ]
 then
@@ -143,7 +146,8 @@ echo
 echo "Copying theory graph from local installation"
 # see the file help/src/DOT for instructions on how to generate the
 # theorygraph files
-/bin/cp $localholdir/help/theorygraph/*.html $localholdir/help/theorygraph/theories.* /tmp/svn-export-result/help/theorygraph
+/bin/cp $localholdir/help/theorygraph/*.html $localholdir/help/theorygraph/theories.* /tmp/svn-export-result/help/theorygraph ||
+  (echo "Couldn't copy theory graph." >&2 ; exit 1)
 
 if [ $ML = "mosml" ]
 then
