----------------------------------------------------------------------
Committing in new version of releasing-hol, which correctly builds the
non-standard documentation for the n_bit library.  The non-standard
part is that the library is named "n_bit" but the documentation is
named "word.{dvi,pdf}".

The documentation is renamed to "<version>-n_bit.{dvi,pdf}" for the
exported, public Kananaskis-3.

Anthony, please review this and let me know if you would like some
corrections.

Modified Files:
	releasing-hol
----------------------------------------------------------------------

diff --git a/developers/releasing-hol b/developers/releasing-hol
--- a/developers/releasing-hol
+++ b/developers/releasing-hol
@@ -104,7 +104,23 @@ do
     mv HolSatLib$i /tmp/$name-HolSatLib$i
 done
 
-for lib_name in n_bit pair pred_set quotient res_quan string taut unwind word
+for lib_name in n_bit
+do
+    echo Building $lib_name documentation
+    cd /tmp/hol98/src/$lib_name/Manual
+    if (make all) > /tmp/$lib_name-latex.log 2>&1
+    then
+       :
+    else
+       echo "Build failed, see /tmp/$lib_name-latex.log" ; exit 1
+    fi
+    for i in .dvi .pdf
+    do
+        mv word$i /tmp/$name-$lib_name$i
+    done
+done
+
+for lib_name in pair pred_set quotient res_quan string taut unwind word
 do
     echo Building $lib_name documentation
     cd /tmp/hol98/src/$lib_name/Manual
